name: CI Selenium Tests | Django/NextJS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install backend dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Get private IP
        id: get_ip
        run: |
          PRIVATE_IP=$(hostname -I | awk '{print $1}')
          echo "Private IP resolved: $PRIVATE_IP"
          echo "HOST_IP=$PRIVATE_IP" >> $GITHUB_ENV

      - name: Start frontend
        env:
          HOST_IP: ${{ env.HOST_IP }}
        run: |
          echo "Starting frontend with environment variables..."
          export NEXT_PUBLIC_API_URL="http://$HOST_IP:8000"

          echo "NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL"

          cd frontend
          npm run start &
          echo "Frontend started."

      - name: Run selenium tests
        env:
          HOST_IP: ${{ env.HOST_IP }}
        run: |
          echo "Running tests..."
          export FRONTEND_URL="http://$HOST_IP:3000"
          cd backend
          python manage.py test
